### ISSUE TITLE
Bug: lastOracleState: overflow for value -20116241

### ISSUE THREAD

**Issue by somes731** [standardsats/plugin-fiat-channels#2]
Actions which lead to suspended channel:

1. Generated invoice to drain channel
2. Realized this invoice is a bit higher than channel balance allows to send
3. Repeated this 4 times and on 4th try channel got suspended

Plugin log:
```
2022-03-28 17:11:27,799 INFO  f.a.e.i.Peer n:02fb13c0d85c7d382bd7155ab1b088dd3a469232efda6df051cf10a8f0c558633a - IN msg=UnknownMessage(53497,ByteVector(38 bytes, 0xefa99f957d7ca657898969522b175c1be6808f1862bb19684dda787025716551000430303033))
2022-03-28 17:11:28,691 ERROR a.a.OneForOneStrategy - lastOracleState: overflow for value -20116241java.lang.IllegalArgumentException: lastOracleState: overflow for value -20116241
  at scodec.Attempt$Failure.require(Attempt.scala:142)
  at scodec.Attempt$Failure.require(Attempt.scala:128)
  at fr.acinq.fc.app.db.HostedChannelsDb.decode(HostedChannelsDb.scala:13)
  at fr.acinq.fc.app.db.HostedChannelsDb.$anonfun$getChannelByRemoteNodeId$2(HostedChannelsDb.scala:38)
  at scala.Option$WithFilter.map(Option.scala:242)
  at fr.acinq.fc.app.db.HostedChannelsDb.getChannelByRemoteNodeId(HostedChannelsDb.scala:37)
  at fr.acinq.fc.app.Worker.restore(Worker.scala:207)
  at fr.acinq.fc.app.Worker$$anonfun$receive$1.applyOrElse(Worker.scala:109)
  at akka.actor.Actor.aroundReceive(Actor.scala:537)
  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
  at fr.acinq.fc.app.Worker.aroundReceive(Worker.scala:44)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
  at akka.actor.ActorCell.invoke(ActorCell.scala:548)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
  at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:678)
  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
  ```

Result: can't restore channel. This is a critical bug since there is no tools to fix it from command line or from the wallet.

**Comment by NCrashed** [comment]
Fixed
